const About = () => {
	return (
		<div style={{ margin: "1rem" }}>
			<div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: '2rem', width: '100%' }}>
				About Page
			</div>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur lacinia eleifend ullamcorper. Pellentesque euismod vestibulum turpis, sit amet consectetur eros malesuada ut. Fusce ac quam vitae justo tincidunt tincidunt. Cras eleifend aliquet lobortis. Nunc ultricies turpis nisl, in aliquam risus commodo sed. Etiam eget volutpat justo, id porttitor risus. Maecenas consectetur enim nibh, eget porta justo eleifend quis. Fusce et nisi vitae tellus ultricies tincidunt fermentum sit amet orci. Vestibulum tincidunt ultrices enim. Donec orci orci, fringilla commodo rhoncus id, placerat sed risus. Donec tincidunt risus erat, ut commodo ex faucibus ac.</p>
			<p>Nulla gravida, justo dictum interdum posuere, odio purus egestas neque, at molestie tellus risus et enim. Morbi id rhoncus velit, quis vestibulum ante. Ut laoreet lacus quis elit sollicitudin, eu bibendum lacus mollis. Pellentesque volutpat est at eros pretium maximus. Ut bibendum, tellus molestie blandit molestie, magna turpis cursus arcu, eu maximus nulla enim ut metus. Pellentesque erat risus, efficitur eu nulla eget, mattis consequat augue. In tempus condimentum velit a bibendum. Curabitur ut augue in purus imperdiet aliquet sit amet ac dolor. Nullam varius, turpis et bibendum ultricies, elit orci laoreet sem, gravida tincidunt nunc ante ut urna.</p>
			<p>Nullam sodales est in ipsum auctor aliquam. Donec interdum pellentesque ipsum, at vulputate diam rhoncus nec. Vivamus id rhoncus quam, et scelerisque nisl. Duis placerat accumsan viverra. Sed efficitur, massa quis tincidunt rutrum, eros nisl viverra nibh, a mattis velit metus in libero. Praesent vitae lorem in nibh sollicitudin ullamcorper vitae suscipit turpis. Nullam vel velit facilisis, vestibulum libero nec, hendrerit augue.</p>
			<p>Nullam dolor leo, interdum eu tortor vel, dictum bibendum odio. Nulla nisl justo, dapibus sagittis orci sit amet, aliquet placerat mi. Sed ullamcorper quam non blandit hendrerit. Nam a urna in turpis vestibulum faucibus a in enim. Fusce sit amet enim nec nisl pretium interdum at non magna. Integer nisi justo, maximus vel magna sit amet, maximus sodales leo. Nullam blandit dapibus porta.</p>
			<p>Pellentesque sed nisi orci. In sit amet quam consectetur, fringilla odio at, elementum nibh. Nulla dapibus mauris eget lorem finibus dapibus. Pellentesque fermentum tempus blandit. Vestibulum tempus et nunc vitae porta. Donec ac nunc orci. Vivamus lorem nulla, eleifend fermentum maximus a, eleifend eget enim. Mauris laoreet dignissim nulla, eget rutrum urna mollis eget. Etiam id eros a urna pharetra ullamcorper. Suspendisse hendrerit ut elit vel sollicitudin.</p>
			<p>Nulla tempus libero purus, sit amet condimentum purus suscipit et. Vivamus pretium augue nec rutrum cursus. Sed euismod rhoncus erat at varius. Morbi varius orci ut sapien tempor commodo. Duis nunc ligula, posuere in augue a, auctor volutpat odio. Duis vulputate ut mi scelerisque pharetra. Ut quis odio nec massa eleifend fermentum vitae sed ipsum. Phasellus ut sem ex. Cras egestas sem quis erat maximus, nec pretium ligula eleifend. Morbi eget arcu luctus, feugiat orci ac, lobortis velit.</p>
			<p>Donec non lobortis nibh. Nulla eget feugiat sem, quis elementum metus. Ut nec tellus tincidunt, tempor tellus in, tristique dolor. Etiam consectetur eros arcu, ac ultricies metus porta id. Ut sollicitudin iaculis turpis in vestibulum. Ut vehicula ante nec enim placerat, eu congue elit convallis. Sed sit amet venenatis felis, sed sollicitudin magna. Vivamus sit amet finibus sapien. Fusce quis leo eu ex sagittis vestibulum. Pellentesque non neque semper, maximus arcu quis, condimentum justo.</p>
			<p>Sed ut ultricies arcu. Etiam bibendum mattis ipsum, et eleifend libero ullamcorper ut. Aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris cursus nisi eu ipsum mattis sollicitudin. Aenean eu rutrum purus. Phasellus sagittis auctor tellus, sed fermentum mauris varius id. Cras maximus pulvinar ligula, vitae blandit ex pretium a. In condimentum ut dui et euismod. Proin non sapien lacus. Nullam ut vehicula ligula. Vestibulum dolor nisl, venenatis in sollicitudin a, blandit id nibh.</p>
			<p>Maecenas et enim quis massa lobortis dapibus. Mauris et blandit leo. Pellentesque commodo rutrum ipsum eget mollis. Nam tincidunt est urna, at scelerisque nunc congue rhoncus. Donec in enim vel odio varius scelerisque a in leo. Maecenas sit amet ipsum eu sem pulvinar cursus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut vel mauris et arcu pulvinar bibendum accumsan sed magna. Maecenas dui magna, semper ut mi dictum, dapibus pretium nulla. Pellentesque est urna, aliquet in urna eget, sodales fermentum nulla. Morbi id scelerisque arcu, vel suscipit lacus. Proin convallis ornare risus.</p>
			<p>Donec sollicitudin ut ex sit amet dignissim. Nunc eget aliquet diam, quis eleifend dui. Sed facilisis a justo sed blandit. Mauris tellus magna, ullamcorper vel porttitor non, ullamcorper ac augue. Morbi sagittis porta lacus, non gravida massa facilisis eu. In pellentesque sagittis magna lobortis vehicula. Vivamus ornare laoreet dignissim. In hac habitasse platea dictumst. Etiam ut tempus nunc, at ultrices ligula. Nulla pulvinar libero vitae tincidunt tempor. Aliquam pellentesque a sapien nec volutpat. Mauris pretium interdum magna, nec congue neque accumsan ut. Phasellus eget purus vestibulum, facilisis elit eu, tristique dolor. Phasellus porta eu quam sed rhoncus. Vivamus et velit dui. Integer vel sollicitudin nisl.</p>
			<p>Nam a sem odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum congue eros sit amet lacus porta, vitae tincidunt turpis molestie. Nam tempor, lorem vel finibus hendrerit, nisl nisi iaculis dui, sit amet aliquam orci augue at diam. Fusce in interdum ligula. Proin in efficitur lacus, sed tincidunt lacus. Donec at mauris sit amet elit fermentum tempor. Sed pellentesque rhoncus velit, eu aliquam lorem hendrerit quis.</p>
			<p>Aliquam at nisl eget tellus posuere vehicula sit amet at sapien. Morbi ullamcorper pharetra suscipit. Cras pellentesque scelerisque dictum. Curabitur vitae libero libero. Vestibulum nec ante ut risus maximus maximus. Cras hendrerit purus ut volutpat malesuada. Praesent tristique lacus odio, nec feugiat augue convallis vehicula. Etiam faucibus nisi nec metus facilisis blandit.</p>
			<p>Vivamus aliquam, neque faucibus posuere ullamcorper, lacus ipsum vulputate nisl, non rutrum orci felis posuere justo. Cras elementum quis felis ut fermentum. Aliquam lacinia, lorem eu mollis interdum, mi sem mollis mi, ac rutrum ante purus ac elit. Donec consequat augue dolor, sed eleifend est tempus vel. Maecenas consequat augue ac viverra pellentesque. Etiam at auctor neque, nec euismod lacus. Nullam arcu leo, tristique vitae viverra malesuada, iaculis at risus. Donec diam nulla, fringilla vestibulum lacinia in, fringilla non orci. Mauris mattis lobortis lectus ac aliquam. Nulla eu aliquam ante.</p>
			<p>Vivamus nec sem lacus. Donec posuere tempor nisl. Morbi varius lacus magna. Proin eu odio imperdiet, tempor arcu id, commodo ante. Sed sit amet felis id ante interdum mattis non vel sapien. Etiam bibendum consectetur dui quis porttitor. Ut sit amet luctus leo. Cras vehicula leo quis felis vestibulum maximus. Sed in dictum ex. Nunc in convallis orci. Praesent eu metus nec lectus lobortis blandit in sit amet ipsum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque imperdiet mollis risus vitae aliquam.</p>
			<p>Cras sit amet lacus sit amet lectus pretium varius eget non libero. Aenean tristique et sem eu lobortis. In vestibulum lacus id nisi vehicula condimentum. Ut justo diam, varius in ante id, consequat molestie arcu. In accumsan magna sem, facilisis aliquet urna dapibus et. Duis auctor volutpat ligula nec cursus. Aliquam erat volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur non eros id est imperdiet mattis. Aenean accumsan quam non odio posuere, in rutrum ipsum porta. Duis facilisis nulla in erat faucibus, in ullamcorper eros molestie. Nam nulla est, consectetur eget neque sed, porttitor elementum felis. Pellentesque commodo, augue vel porttitor viverra, augue ligula interdum lectus, sed vestibulum mauris nunc at ante.</p>
			<p>Integer eget nisi ut metus pulvinar iaculis vel in libero. Suspendisse in bibendum magna. Mauris iaculis imperdiet gravida. Sed et mauris ultrices, molestie erat vel, mollis velit. Suspendisse condimentum mollis varius. Vestibulum luctus, felis vel accumsan volutpat, risus metus sodales ipsum, nec facilisis massa lorem in erat. Duis nec felis nibh. Praesent id semper odio. Donec pulvinar ante id neque aliquet auctor. Sed vitae odio nec sem dictum tristique. In ut velit vel nisi imperdiet imperdiet.</p>
			<p>Curabitur quis varius sapien. Vivamus sit amet fringilla sem. Vestibulum scelerisque orci porta massa scelerisque fermentum. Duis maximus dui ex, a egestas velit tempor vitae. Maecenas ac metus tincidunt, eleifend lectus sit amet, dictum nulla. Sed eleifend est non odio sollicitudin mattis. Mauris posuere tellus ligula, ac feugiat augue sodales ut. Cras in condimentum neque, ut fermentum nisi. Pellentesque non nisl imperdiet lacus hendrerit varius.</p>
			<p>Cras sit amet lectus eget velit consequat efficitur elementum et tellus. Vestibulum malesuada ullamcorper sem, ac vulputate elit interdum nec. Aliquam vitae fermentum tellus. Ut faucibus lectus ac felis molestie, ut sagittis diam posuere. Duis vitae nibh arcu. Phasellus at diam non odio auctor porta quis ut lectus. Nunc luctus posuere suscipit.</p>
			<p>Morbi suscipit odio purus, ac laoreet lectus facilisis eget. Quisque aliquam ligula eget lacus ultricies, ac pharetra risus tincidunt. Suspendisse posuere, dui vel vestibulum tincidunt, neque mauris laoreet massa, ut imperdiet sem sapien at nunc. Sed eros orci, vulputate sed blandit quis, fringilla nec tortor. Aenean hendrerit ipsum sapien, non semper odio iaculis id. Praesent interdum dictum dictum. Sed vulputate blandit odio elementum tincidunt. Fusce tristique id mauris non pretium. Morbi id turpis sit amet augue rutrum lacinia. Proin ut turpis vitae magna laoreet pellentesque ac eget ex. Nullam sed nisl a ligula vehicula ultricies. Ut at tempus nulla.</p>
			<p>Aliquam dignissim orci risus, eget aliquet est hendrerit eu. Cras diam ex, egestas in lacinia sagittis, pretium sed massa. Fusce convallis turpis felis, eu rutrum mauris dignissim at. Pellentesque commodo sollicitudin nunc a volutpat. Vestibulum aliquet efficitur mi nec placerat. Suspendisse ut metus ex. Cras auctor condimentum ultricies. Cras convallis, metus sit amet consectetur iaculis, justo felis dictum massa, eu lacinia odio lectus eget leo. Vivamus auctor nibh risus, eu convallis nisi iaculis id. Nulla quis molestie diam, at euismod diam. Morbi pulvinar lorem volutpat, sollicitudin metus at, suscipit felis. Proin ac augue vel diam tincidunt facilisis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed imperdiet non augue nec sollicitudin. Mauris interdum iaculis ex non ornare.</p>
		</div>
	);
};

export default About;